#!/usr/bin/env bash
#
# Sync OCTO server secrets from Google Secret Manager into ./.env  (WS-0.3).
#
# Runs ON the host (mytrip-prod, or staging). Uses the box's GSM-reader SA. Writes
# a 600 .env with non-secret config + the secrets. NEVER prints secret values.
# Rotate secrets in GSM — never hand-edit .env (the next sync overwrites it).
#
# GSM secrets:
#   platform_ventrata_octo_api_key   REQUIRED — the Ventrata OCTO Bearer key
#   platform_octo_facade_token       OPTIONAL — internal Express<->facade bearer
#   platform_anthropic_api_key       OPTIONAL — web-chat brain (absent => deterministic)
# A REQUIRED secret missing aborts the sync. An OPTIONAL one missing is skipped with a
# warning (its line is omitted from .env), so the live Ventrata supplier stays durable
# even before the facade/anthropic secrets are provisioned.
#
set -euo pipefail

PROJECT="${GCP_PROJECT:-mytrip-prod-2026}"
SA="${GSM_SA_KEY_FILE:-/etc/gcp/production-gsm-reader.json}"
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"
export GOOGLE_APPLICATION_CREDENTIALS="$SA"

command -v gcloud >/dev/null || { echo "gcloud not found on PATH" >&2; exit 1; }
[ -r "$SA" ] || { echo "GSM SA key not readable: $SA" >&2; exit 1; }

# env var  ->  GSM secret name
declare -A SECRETS=(
  [VENTRATA_OCTO_API_KEY]="platform_ventrata_octo_api_key"
  [OCTO_FACADE_TOKEN]="platform_octo_facade_token"
  [ANTHROPIC_API_KEY]="platform_anthropic_api_key"
)
# Secrets whose absence is fatal (the rest are skipped with a warning).
REQUIRED=( VENTRATA_OCTO_API_KEY )
is_required() { local v; for v in "${REQUIRED[@]}"; do [ "$v" = "$1" ] && return 0; done; return 1; }

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by scripts/sync-secrets.sh — DO NOT hand-edit secrets (rotate in GSM)."
  echo "HOST=127.0.0.1"
  echo "PORT=8790"
  echo "OCTO_ALLOWED_HOSTS=octo.mytrip.ai"
  echo "OCTO_PUBLIC_URL=https://octo.mytrip.ai"
  echo "VENTRATA_OCTO_ENDPOINT=https://api.ventrata.com/octo"
  echo "VENTRATA_OCTO_CURRENCY=GBP"
} > "$tmp"

written=0
for var in "${!SECRETS[@]}"; do
  if ! val="$(gcloud secrets versions access latest --secret="${SECRETS[$var]}" --project="$PROJECT" 2>/dev/null)"; then
    if is_required "$var"; then
      echo "FAILED to fetch REQUIRED GSM secret '${SECRETS[$var]}' (does it exist?)" >&2
      exit 1
    fi
    echo "skip: optional secret '${SECRETS[$var]}' not found — omitting $var" >&2
    continue
  fi
  printf '%s=%s\n' "$var" "$val" >> "$tmp"
  written=$((written + 1))
done

install -m 600 "$tmp" "$ENV_FILE"
echo "Wrote $ENV_FILE — $written secret(s) + config (values not printed)."
