#!/usr/bin/env bash
#
# Sync OCTO server secrets from Google Secret Manager into ./.env  (WS-0.3).
#
# Runs ON the host (mytrip-prod, or staging). Uses the box's GSM-reader SA. Writes
# a 600 .env with non-secret config + the secrets. NEVER prints secret values.
# Rotate secrets in GSM — never hand-edit .env (the next sync overwrites it).
#
# ⚠️ The three GSM secrets below must EXIST first (create them as part of WS-0.3):
#     platform_ventrata_octo_api_key   (the Ventrata OCTO Bearer key)
#     platform_octo_facade_token       (NEW: internal Express<->facade bearer)
#     platform_anthropic_api_key       (web-chat brain; confirm the canonical name)
#
set -euo pipefail

PROJECT="${GCP_PROJECT:-mytrip-prod-2026}"
SA="${GSM_SA_KEY_FILE:-/etc/gcp/production-gsm-reader.json}"
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"
export GOOGLE_APPLICATION_CREDENTIALS="$SA"

command -v gcloud >/dev/null || { echo "gcloud not found on PATH" >&2; exit 1; }
[ -r "$SA" ] || { echo "GSM SA key not readable: $SA" >&2; exit 1; }

# env var  ->  GSM secret name
declare -A SECRETS=(
  [VENTRATA_OCTO_API_KEY]="platform_ventrata_octo_api_key"
  [OCTO_FACADE_TOKEN]="platform_octo_facade_token"
  [ANTHROPIC_API_KEY]="platform_anthropic_api_key"
)

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by scripts/sync-secrets.sh — DO NOT hand-edit secrets (rotate in GSM)."
  echo "HOST=127.0.0.1"
  echo "PORT=8790"
  echo "OCTO_ALLOWED_HOSTS=octo.mytrip.ai"
  echo "OCTO_PUBLIC_URL=https://octo.mytrip.ai"
  echo "VENTRATA_OCTO_ENDPOINT=https://api.ventrata.com/octo"
  echo "VENTRATA_OCTO_CURRENCY=GBP"
} > "$tmp"

for var in "${!SECRETS[@]}"; do
  if ! val="$(gcloud secrets versions access latest --secret="${SECRETS[$var]}" --project="$PROJECT" 2>/dev/null)"; then
    echo "FAILED to fetch GSM secret '${SECRETS[$var]}' (does it exist?)" >&2
    exit 1
  fi
  printf '%s=%s\n' "$var" "$val" >> "$tmp"
done

install -m 600 "$tmp" "$ENV_FILE"
echo "Wrote $ENV_FILE — ${#SECRETS[@]} secret(s) + config (values not printed)."
